version: "3"
services: 
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: Animazon-client
    ports: 
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: Animazon-server
    ports: 
      - 4000:4000
    environment: 
      - CHOKIDAR_USEPOLLING=true